import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Image } from "expo-image";
import * as Clipboard from "expo-clipboard";
import { Check, Copy, QrCode } from "lucide-react-native";
import { AppHeader } from "@/src/components/ui";
import { makeReferralCode } from "@/src/lib/referral";
import { useAuth } from "@/src/providers/auth";

const MAROON = "#6E262B";
export default function ReferralCodeScreen() { const { user } = useAuth(); const [copied, setCopied] = useState<"code" | "link">(); if (!user) return null; const code = makeReferralCode(user.customerId), link = `https://wearify.app/register?inviteCode=${code}`; const copy = async (value: string, kind: "code" | "link") => { await Clipboard.setStringAsync(value); setCopied(kind); setTimeout(() => setCopied(undefined), 1800); }; return <View style={styles.page}><AppHeader back title="REFER A FRIENDS" /><ScrollView contentContainerStyle={styles.content}><Text style={styles.heading}>Invite Friends</Text><Image source={require("@/assets/customer/refer-friend/card-2.svg")} style={styles.banner} contentFit="contain" accessibilityLabel="Earn ₹500 per referral" /><Text style={styles.sectionTitle}>Your Referral Code</Text><Pressable style={styles.code} onPress={() => void copy(code, "code")}><Text selectable style={styles.codeText}>{code}</Text>{copied === "code" ? <Check size={18} color="#1E7A3D" strokeWidth={2.6} /> : <Copy size={17} color="#9A8F8A" />}</Pressable><Text style={styles.sectionTitle}>Your QR Code</Text><View style={styles.qr}><QrCode size={146} color="#F5ECD7" strokeWidth={1.4} /></View><Text style={styles.sectionTitle}>Your Referral Link</Text><View style={styles.link}><Text numberOfLines={1} style={styles.linkText}>{link}</Text><Pressable accessibilityLabel="Copy link" style={[styles.copyButton, copied === "link" && styles.copied]} onPress={() => void copy(link, "link")}>{copied === "link" ? <Check size={18} color="#1E7A3D" strokeWidth={2.6} /> : <Copy size={17} color="#5A4F48" />}</Pressable></View></ScrollView></View>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#FFFFFF" }, content: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 32 }, heading: { marginBottom: 16, fontFamily: "DMSans_700Bold", fontSize: 24, letterSpacing: -0.24, color: "#1C1714" }, banner: { width: "100%", aspectRatio: 361 / 153, marginBottom: 28 }, sectionTitle: { marginBottom: 14, fontFamily: "DMSans_700Bold", fontSize: 19, color: "#1C1714", textAlign: "center" }, code: { minWidth: 230, alignSelf: "center", marginBottom: 30, paddingHorizontal: 32, paddingVertical: 16, borderRadius: 12, borderWidth: 1.5, borderColor: "rgba(104,38,42,0.18)", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10 }, codeText: { fontFamily: "DMSans_700Bold", fontSize: 22, letterSpacing: 3.08, color: MAROON }, qr: { width: 200, height: 200, marginBottom: 30, alignSelf: "center", borderRadius: 28, backgroundColor: MAROON, alignItems: "center", justifyContent: "center", shadowColor: MAROON, shadowOpacity: 0.22, shadowRadius: 13, shadowOffset: { width: 0, height: 10 }, elevation: 5 }, link: { minHeight: 62, paddingLeft: 18, paddingRight: 10, borderRadius: 31, borderWidth: 1.5, borderColor: "rgba(104,38,42,0.16)", flexDirection: "row", alignItems: "center", gap: 8 }, linkText: { flex: 1, fontFamily: "DMSans_400Regular", fontSize: 13.5, color: "#5A4F48" }, copyButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#F4ECE9", alignItems: "center", justifyContent: "center" }, copied: { backgroundColor: "#E3F4E8" } });
