import { useState } from "react";
import { Alert, Linking, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Image } from "expo-image";
import { useRouter } from "expo-router";
import { useMutation, useQuery } from "convex/react";
import { api } from "@/src/convex/api";
import { AppHeader, Loading } from "@/src/components/ui";
import { makeReferralCode } from "@/src/lib/referral";
import { useAuth } from "@/src/providers/auth";
import { useIsOnline } from "@/src/providers/connectivity";

const MAROON = "#6E262B";
export default function ReferScreen() {
  const router = useRouter(); const online = useIsOnline(); const { token, user } = useAuth(); const referrals = useQuery(api.customers.listReferrals, token && user ? { token, referrerId: user.customerId } : "skip"); const create = useMutation(api.customers.createReferral); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [busy, setBusy] = useState(false);
  if (!user || referrals === undefined) return <><AppHeader back title="REFER A FRIENDS" /><Loading /></>;
  const referrer = user, code = makeReferralCode(referrer.customerId), link = `https://wearify.app/register?inviteCode=${code}`, message = `Hey! Shop at any Wearify-powered store and we both get ₹500 credit. Use my code ${code} or sign up here: ${link}`;
  async function submit() { if (!online) return Alert.alert("You’re offline", "Reconnect to send a referral."); if (!token || name.trim().length < 2 || phone.trim().length < 8) return; setBusy(true); try { await create({ token, referrerId: referrer.customerId, referrerPhone: referrer.phone, referredName: name.trim(), referredPhone: phone.trim(), status: "Pending", date: new Date().toLocaleDateString("en-IN", { year: "numeric", month: "short", day: "numeric" }) }); router.push("/c/me/refer/code"); } catch { Alert.alert("Couldn’t create referral", "Please check the phone number and try again."); } finally { setBusy(false); } }
  return <View style={styles.page}><AppHeader back title="REFER A FRIENDS" /><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.heading}>Invite Friends</Text><Image source={require("@/assets/customer/refer-friend/card-1.svg")} style={styles.banner} contentFit="contain" accessibilityLabel="Earn ₹500 per referral" /><Text style={styles.sectionTitle}>Send a referral</Text><TextInput style={styles.field} placeholder="Friend's name" placeholderTextColor="#9A8F8A" value={name} onChangeText={setName} /><TextInput style={styles.field} placeholder="Friend's phone number" placeholderTextColor="#9A8F8A" keyboardType="phone-pad" value={phone} onChangeText={setPhone} /><Pressable disabled={busy || name.trim().length < 2 || phone.trim().length < 8} style={[styles.send, (busy || name.trim().length < 2 || phone.trim().length < 8) && styles.disabled]} onPress={() => void submit()}><Text style={styles.buttonText}>{busy ? "Sending…" : "Send Referral"}</Text></Pressable><Pressable style={styles.whatsappButton} onPress={() => void Linking.openURL(`https://wa.me/?text=${encodeURIComponent(message)}`)}><Image source={require("@/assets/customer/refer-friend/whatsapp.svg")} style={styles.whatsappIcon} contentFit="contain" /><Text style={styles.buttonText}>Share to WhatsApp</Text></Pressable><Text style={[styles.sectionTitle, styles.historyTitle]}>Referral History</Text>{referrals.length ? <View style={styles.history}>{referrals.map((item) => { const status = item.status || "Pending", palette = status === "Rewarded" ? ["#E3F4E8", "#1E7A3D"] : status === "Visited" ? ["#FAF1DD", "#7A5A08"] : ["#F4ECE9", "#9A8F8A"]; return <View key={item._id} style={styles.row}><View style={styles.rowCopy}><Text numberOfLines={1} style={styles.name}>{item.referredName || "Friend"}</Text><Text style={styles.date}>{item.date || ""}</Text></View>{item.reward && item.reward > 0 ? <Text style={styles.reward}>+{item.reward} pts</Text> : null}<View style={[styles.status, { backgroundColor: palette[0] }]}><Text style={[styles.statusText, { color: palette[1] }]}>{status}</Text></View></View>; })}</View> : <Text style={styles.empty}>No referrals yet. Send one to get started!</Text>}</ScrollView></View>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#FFFFFF" }, content: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 32 }, heading: { marginBottom: 16, fontFamily: "DMSans_700Bold", fontSize: 24, letterSpacing: -0.24, color: "#1C1714" }, banner: { width: "100%", aspectRatio: 361 / 153, marginBottom: 26 }, sectionTitle: { marginBottom: 14, fontFamily: "DMSans_700Bold", fontSize: 19, color: "#1C1714" }, field: { height: 56, marginBottom: 12, paddingHorizontal: 16, borderRadius: 12, borderWidth: 1.5, borderColor: "rgba(104,38,42,0.16)", backgroundColor: "#FFFFFF", fontFamily: "DMSans_400Regular", fontSize: 16, color: "#2A2522" }, send: { height: 56, marginTop: 4, marginBottom: 12, borderRadius: 12, backgroundColor: MAROON, alignItems: "center", justifyContent: "center" }, disabled: { opacity: 0.6 }, buttonText: { fontFamily: "DMSans_700Bold", fontSize: 16, color: "#FFFFFF" }, whatsappButton: { height: 56, borderRadius: 12, backgroundColor: "#42C152", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10 }, whatsappIcon: { width: 24, height: 24 }, historyTitle: { marginTop: 26 }, history: { gap: 8 }, row: { minHeight: 62, paddingHorizontal: 14, paddingVertical: 12, borderRadius: 14, borderWidth: 1, borderColor: "#F0E6E3", backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center", gap: 8, shadowColor: "#000000", shadowOpacity: 0.05, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 2 }, rowCopy: { flex: 1, minWidth: 0 }, name: { fontFamily: "DMSans_600SemiBold", fontSize: 14, color: "#2A2522" }, date: { marginTop: 2, fontFamily: "DMSans_400Regular", fontSize: 11.5, color: "#9A8F8A" }, reward: { fontFamily: "DMSans_700Bold", fontSize: 12, color: "#B8860B" }, status: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: 10 }, statusText: { fontFamily: "DMSans_700Bold", fontSize: 11 }, empty: { paddingVertical: 28, fontFamily: "DMSans_400Regular", fontSize: 13, color: "#9A8F8A", textAlign: "center" } });
