import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { useMutation, useQuery } from "convex/react";
import { MapPin, Star } from "lucide-react-native";
import { api } from "@/src/convex/api";
import { AppHeader, EmptyState, Field, Loading, PrimaryButton, Screen, Title } from "@/src/components/ui";
import { useAuth } from "@/src/providers/auth";
import { useIsOnline } from "@/src/providers/connectivity";
import { colors, radius } from "@/src/theme/tokens";

export default function FeedbackScreen() {
  const { token, user } = useAuth(); const online = useIsOnline(); const stores = useQuery(api.customers.listStoreLinksEnriched, token && user ? { token, customerId: user.customerId } : "skip"); const submit = useMutation(api.customers.submitFeedback);
  const [selected, setSelected] = useState<number>(); const [rating, setRating] = useState(0); const [comment, setComment] = useState(""); const [busy, setBusy] = useState(false);
  if (stores === undefined) return <><AppHeader back title="Rate your visit" /><Loading /></>;
  const store = selected === undefined ? undefined : stores[selected];
  async function save() { if (!online) return Alert.alert("You’re offline", "Reconnect to send feedback."); if (!store || !token || !user || rating === 0) return; setBusy(true); try { await submit({ token, customerId: user.customerId, customerPhone: user.phone, storeId: store.storeId, rating, comment: comment.trim() || undefined, date: new Date().toISOString().slice(0, 10) }); Alert.alert("Thank you", "Your feedback has been submitted."); setSelected(undefined); setRating(0); setComment(""); } catch { Alert.alert("Couldn’t submit", "Please try again."); } finally { setBusy(false); } }
  return <><AppHeader back title="Rate your visit" /><Screen><Title subtitle="Tell connected stores about your experience">Feedback</Title>{stores.length === 0 ? <EmptyState title="No connected stores" detail="Your stores will appear after a Wearify visit." /> : store ? <View style={styles.card}><Text style={styles.name}>{store.storeName ?? store.storeId}</Text><View style={styles.location}><MapPin size={14} color={colors.muted} /><Text style={styles.meta}>{store.storeAddress ?? store.storeCity ?? "Wearify store"}</Text></View><Text style={styles.prompt}>How was your experience?</Text><View style={styles.stars}>{[1, 2, 3, 4, 5].map((value) => <Pressable accessibilityRole="radio" accessibilityLabel={`${value} stars`} accessibilityState={{ checked: rating === value }} hitSlop={8} key={value} onPress={() => setRating(value)}><Star size={34} color="#B8860B" fill={value <= rating ? "#B8860B" : "transparent"} /></Pressable>)}</View><Field label="Comment (optional)" value={comment} onChangeText={setComment} multiline maxLength={500} /><PrimaryButton disabled={rating === 0 || busy} onPress={() => void save()}>{busy ? "Submitting…" : "Submit feedback"}</PrimaryButton></View> : stores.map((item, index) => <Pressable accessibilityRole="button" key={item._id} style={styles.store} onPress={() => setSelected(index)}><MapPin color={colors.brand} size={20} /><View style={{ flex: 1 }}><Text style={styles.name}>{item.storeName ?? item.storeId}</Text><Text style={styles.meta}>{item.lastVisit ? `Last visit ${item.lastVisit}` : item.storeCity ?? "Tap to rate"}</Text></View></Pressable>)}</Screen></>;
}
const styles = StyleSheet.create({ card: { padding: 18, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, store: { minHeight: 72, marginBottom: 10, padding: 14, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: colors.surface }, name: { color: colors.ink, fontFamily: "Montserrat_600SemiBold", fontSize: 15 }, meta: { color: colors.muted, fontFamily: "DMSans_400Regular", fontSize: 12, marginTop: 3 }, location: { flexDirection: "row", alignItems: "center", gap: 5 }, prompt: { marginTop: 28, textAlign: "center", color: colors.ink, fontFamily: "CormorantGaramond_700Bold", fontSize: 24 }, stars: { flexDirection: "row", justifyContent: "center", gap: 8, marginVertical: 20 } });
