import { StyleSheet, Text, View } from "react-native";
import { useQuery } from "convex/react";
import { Award, WalletCards } from "lucide-react-native";
import { api } from "@/src/convex/api";
import { AppHeader, EmptyState, Loading, Screen, Title } from "@/src/components/ui";
import { useAuth } from "@/src/providers/auth";
import { colors, radius } from "@/src/theme/tokens";

export default function LoyaltyScreen() { const { token, user, customer } = useAuth(); const txns = useQuery(api.customers.getLoyaltyTransactions, token && user ? { token, customerId: user.customerId } : "skip"); if (txns === undefined) return <><AppHeader back title="Loyalty credits" /><Loading /></>; return <><AppHeader back title="Loyalty credits" /><Screen><Title subtitle="Rewards from your Wearify visits">Loyalty Credits</Title><View style={styles.wallet}><WalletCards color="#F7D58C" size={30} /><Text style={styles.points}>{customer?.loyaltyPoints ?? 0}</Text><Text style={styles.pointsLabel}>available points</Text><View style={styles.tier}><Award color="#F7D58C" size={14} /><Text style={styles.tierText}>{customer?.loyaltyTier ?? "Member"}</Text></View></View><Text style={styles.section}>Recent activity</Text>{txns.length === 0 ? <EmptyState title="No transactions yet" /> : txns.map((item) => <View key={item._id} style={styles.row}><View><Text style={styles.reason}>{item.reason ?? item.storeName ?? "Wearify reward"}</Text><Text style={styles.date}>{item.date ?? ""}</Text></View><Text style={[styles.delta, (item.points ?? 0) < 0 && styles.negative]}>{(item.points ?? 0) > 0 ? "+" : ""}{item.points ?? 0}</Text></View>)}</Screen></>; }
const styles = StyleSheet.create({ wallet: { padding: 24, borderRadius: radius.lg, backgroundColor: colors.brand, alignItems: "center" }, points: { marginTop: 12, color: "#FFFFFF", fontFamily: "Montserrat_700Bold", fontSize: 40 }, pointsLabel: { color: "rgba(255,255,255,.75)", fontFamily: "DMSans_400Regular", fontSize: 12 }, tier: { marginTop: 12, paddingHorizontal: 12, paddingVertical: 6, borderRadius: radius.pill, backgroundColor: "rgba(255,255,255,.12)", flexDirection: "row", alignItems: "center", gap: 6 }, tierText: { color: "#F7D58C", fontFamily: "DMSans_600SemiBold", fontSize: 12 }, section: { marginTop: 26, marginBottom: 12, color: colors.ink, fontFamily: "Montserrat_600SemiBold", fontSize: 16 }, row: { minHeight: 62, marginBottom: 8, padding: 13, borderRadius: radius.md, backgroundColor: colors.surface, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, reason: { color: colors.ink, fontFamily: "DMSans_600SemiBold", fontSize: 13 }, date: { marginTop: 3, color: colors.muted, fontFamily: "DMSans_400Regular", fontSize: 11 }, delta: { color: colors.success, fontFamily: "Montserrat_700Bold", fontSize: 15 }, negative: { color: colors.error } });
