import { useEffect, useRef, useState, type ReactNode } from "react";
import { Alert, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import DateTimePicker from "@react-native-community/datetimepicker";
import { useMutation } from "convex/react";
import { Calendar, Check, ChevronDown } from "lucide-react-native";
import { api } from "@/src/convex/api";
import { AppHeader } from "@/src/components/ui";
import { useAuth } from "@/src/providers/auth";
import { useIsOnline } from "@/src/providers/connectivity";

const MAROON = "#6E262B";
const OCCASIONS = ["Wedding", "Festival", "Party", "Office", "Daily", "Gift"];
const FABRICS = ["Pure Silk", "Georgette", "Cotton", "Linen", "Chanderi", "Banarasi", "Kanjivaram", "Tussar"];
const COLORS = [["Crimson", "#DC143C"], ["Purple", "#7B3FA0"], ["Gold", "#E0A800"], ["Green", "#2D8544"], ["Blue", "#1F5FE0"], ["Pink", "#F4B9CD"], ["Black", "#1A1A1A"], ["White", "#FFFFFF"]] as const;
const BUDGETS = ["Under ₹5,000", "₹5,000–₹15,000", "₹15,000–₹30,000", "₹30,000–₹50,000", "Above ₹50,000"];

export default function PreferencesScreen() {
  const online = useIsOnline(); const { token, user, customer } = useAuth(); const update = useMutation(api.customers.updatePreferences);
  const hydrated = useRef(false); const [occasions, setOccasions] = useState<string[]>([]); const [fabrics, setFabrics] = useState<string[]>([]); const [colors, setColors] = useState<string[]>([]); const [location, setLocation] = useState(""); const [budget, setBudget] = useState(""); const [upcoming, setUpcoming] = useState(""); const [date, setDate] = useState(""); const [showDate, setShowDate] = useState(false); const [showBudget, setShowBudget] = useState(false); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false);
  useEffect(() => { if (!customer || hydrated.current) return; hydrated.current = true; setOccasions(customer.preferredOccasions || []); setFabrics(customer.preferredFabrics || []); setColors(customer.preferredColors || []); setLocation(customer.city || ""); setBudget(customer.budgetRange || ""); setUpcoming(customer.upcomingOccasion || ""); setDate(customer.upcomingOccasionDate || ""); }, [customer]);
  const toggle = (list: string[], value: string, set: (next: string[]) => void) => { set(list.includes(value) ? list.filter((item) => item !== value) : [...list, value]); setSaved(false); };
  async function save() { if (!token || !user) return; if (!online) return Alert.alert("You’re offline", "Reconnect to save preferences."); setSaving(true); try { await update({ token, customerId: user.customerId, preferredOccasions: occasions, preferredFabrics: fabrics, preferredColors: colors, budgetRange: budget || undefined, upcomingOccasion: upcoming || undefined, upcomingOccasionDate: date || undefined, city: location.trim() || undefined }); setSaved(true); setTimeout(() => setSaved(false), 2500); } catch { Alert.alert("Couldn’t save preferences", "Please try again."); } finally { setSaving(false); } }
  return <View style={styles.page}><AppHeader back title="MY PREFERENCE" /><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <Section title="Occasions"><View style={styles.wrap}>{OCCASIONS.map((item) => <Pill key={item} active={occasions.includes(item)} onPress={() => toggle(occasions, item, setOccasions)}>{item}</Pill>)}</View></Section>
    <Section title="Fabrics"><View style={styles.wrap}>{FABRICS.map((item) => <Pill key={item} active={fabrics.includes(item)} onPress={() => toggle(fabrics, item, setFabrics)}>{item}</Pill>)}</View></Section>
    <Section title="Colors"><View style={styles.wrap}>{COLORS.map(([name, swatch]) => <ColorPill key={name} name={name} swatch={swatch} active={colors.includes(name)} onPress={() => toggle(colors, name, setColors)} />)}</View></Section>
    <Section title="Location"><TextInput style={styles.field} placeholder="eg:- Mumbai" placeholderTextColor="#9A8F8A" value={location} onChangeText={(value) => { setLocation(value); setSaved(false); }} /></Section>
    <Section title="Budget Range"><Pressable style={styles.select} onPress={() => setShowBudget(true)}><Text style={[styles.selectText, !budget && styles.placeholder]}>{budget || "Select budget"}</Text><ChevronDown size={17} color={MAROON} /></Pressable></Section>
    <Section title="Upcoming Occasion"><View style={styles.upcoming}><TextInput style={[styles.field, styles.upcomingField]} placeholder="eg.Daughter wedding" placeholderTextColor="#9A8F8A" value={upcoming} onChangeText={(value) => { setUpcoming(value); setSaved(false); }} /><Pressable style={styles.dateField} onPress={() => setShowDate(true)}><Text numberOfLines={1} style={[styles.dateText, !date && styles.placeholder]}>{date || "Date"}</Text><Calendar size={17} color={MAROON} /></Pressable></View></Section>
    <Pressable disabled={saving} style={[styles.save, saving && styles.disabled]} onPress={() => void save()}><Text style={styles.saveText}>{saving ? "Saving…" : saved ? "Saved Preferences" : "Save Preferences"}</Text>{saved ? <Check size={18} color="#FFFFFF" strokeWidth={2.6} /> : null}</Pressable>
  </ScrollView>
  {showDate ? <DateTimePicker value={date ? new Date(`${date}T00:00:00`) : new Date()} mode="date" onChange={(_, selected) => { setShowDate(Platform.OS === "ios"); if (selected) { setDate(selected.toISOString().slice(0, 10)); setSaved(false); } }} /> : null}
  <Modal visible={showBudget} transparent animationType="fade" onRequestClose={() => setShowBudget(false)}><Pressable style={styles.modal} onPress={() => setShowBudget(false)}><View style={styles.budgetCard}>{BUDGETS.map((item) => <Pressable key={item} style={[styles.budgetRow, budget === item && styles.budgetActive]} onPress={() => { setBudget(item); setSaved(false); setShowBudget(false); }}><Text style={[styles.budgetText, budget === item && styles.budgetTextActive]}>{item}</Text></Pressable>)}</View></Pressable></Modal>
  </View>;
}

function Section({ title, children }: { title: string; children: ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
function Pill({ active, onPress, children }: { active: boolean; onPress: () => void; children: ReactNode }) { return <Pressable style={[styles.pill, active && styles.pillActive]} onPress={onPress}><Text style={[styles.pillText, active && styles.pillTextActive]}>{children}</Text></Pressable>; }
function ColorPill({ name, swatch, active, onPress }: { name: string; swatch: string; active: boolean; onPress: () => void }) { return <Pressable style={[styles.pill, active && styles.pillActive]} onPress={onPress}><View style={[styles.swatch, { backgroundColor: swatch }, name === "White" && styles.whiteSwatch]} /><Text style={[styles.pillText, active && styles.pillTextActive]}>{name}</Text></Pressable>; }

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#FFFFFF" }, content: { paddingHorizontal: 18, paddingTop: 20, paddingBottom: 36 }, section: { marginBottom: 24 }, sectionTitle: { marginBottom: 12, fontFamily: "DMSans_700Bold", fontSize: 18, color: "#2A2522" }, wrap: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, pill: { minHeight: 38, paddingHorizontal: 16, paddingVertical: 9, borderRadius: 19, borderWidth: 1, borderColor: "rgba(104,38,42,0.18)", backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center", gap: 7 }, pillActive: { borderColor: MAROON, backgroundColor: MAROON }, pillText: { fontFamily: "DMSans_600SemiBold", fontSize: 13.5, color: "#2A2522" }, pillTextActive: { color: "#FFFFFF" }, swatch: { width: 16, height: 16, borderRadius: 8, borderWidth: 1, borderColor: "rgba(0,0,0,0.1)" }, whiteSwatch: { borderColor: "#D8C9BC" }, field: { height: 52, paddingHorizontal: 16, borderRadius: 12, borderWidth: 1.5, borderColor: "rgba(104,38,42,0.14)", backgroundColor: "#FFFFFF", fontFamily: "DMSans_400Regular", fontSize: 16, color: "#2A2522" }, select: { height: 52, paddingHorizontal: 16, borderRadius: 12, borderWidth: 1.5, borderColor: "rgba(104,38,42,0.14)", flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, selectText: { fontFamily: "DMSans_400Regular", fontSize: 16, color: "#2A2522" }, placeholder: { color: "#9A8F8A" }, upcoming: { flexDirection: "row", gap: 10 }, upcomingField: { flex: 1, minWidth: 0 }, dateField: { width: 140, height: 52, paddingHorizontal: 12, borderRadius: 12, borderWidth: 1.5, borderColor: "rgba(104,38,42,0.14)", flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, dateText: { flex: 1, fontFamily: "DMSans_400Regular", fontSize: 13, color: "#2A2522" }, save: { height: 56, marginTop: 2, borderRadius: 14, backgroundColor: MAROON, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, shadowColor: MAROON, shadowOpacity: 0.26, shadowRadius: 11, shadowOffset: { width: 0, height: 8 }, elevation: 5 }, saveText: { fontFamily: "DMSans_700Bold", fontSize: 16, color: "#FFFFFF" }, disabled: { opacity: 0.75 }, modal: { flex: 1, padding: 24, backgroundColor: "rgba(0,0,0,0.45)", alignItems: "center", justifyContent: "center" }, budgetCard: { width: "100%", maxWidth: 340, overflow: "hidden", borderRadius: 16, backgroundColor: "#FFFFFF" }, budgetRow: { minHeight: 52, paddingHorizontal: 18, justifyContent: "center", borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: "#E8E0DD" }, budgetActive: { backgroundColor: MAROON }, budgetText: { fontFamily: "DMSans_600SemiBold", fontSize: 15, color: "#2A2522" }, budgetTextActive: { color: "#FFFFFF" } });
