import { useEffect, useState } from "react";
import { Alert, StyleSheet, Switch, Text, View } from "react-native";
import * as ScreenCapture from "expo-screen-capture";
import * as Sharing from "expo-sharing";
import { File, Paths } from "expo-file-system";
import { useConvex, useMutation, useQuery } from "convex/react";
import { api } from "@/src/convex/api";
import { AppHeader, Loading, PrimaryButton, Screen, SecondaryButton, Title } from "@/src/components/ui";
import { useAuth } from "@/src/providers/auth";
import { useIsOnline } from "@/src/providers/connectivity";
import { colors, radius } from "@/src/theme/tokens";

export default function PrivacyScreen() {
  ScreenCapture.usePreventScreenCapture();
  const auth = useAuth(); const { token, user } = auth; const online = useIsOnline(); const convex = useConvex();
  const customer = useQuery(api.customers.getById, token && user ? { token, customerId: user.customerId } : "skip");
  const update = useMutation(api.customers.updateConsent); const remove = useMutation(api.customers.deleteMyData);
  const [history, setHistory] = useState(true); const [messages, setMessages] = useState(true); const [personal, setPersonal] = useState(true); const [photos, setPhotos] = useState(true); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!customer) return; setHistory(customer.consentHistory ?? true); setMessages(customer.consentMessages ?? true); setPersonal(customer.consentAiPersonal ?? true); setPhotos(customer.consentPhotos ?? true); }, [customer]);
  const guard = () => { if (online) return true; Alert.alert("You’re offline", "Reconnect to manage privacy or data."); return false; };
  async function save() { if (!guard() || !token || !user) return; setBusy(true); try { await update({ token, customerId: user.customerId, consentHistory: history, consentMessages: messages, consentAiPersonal: personal, consentPhotos: photos, consentGrantedDate: new Date().toISOString().slice(0, 10) }); Alert.alert("Saved", "Your privacy choices are updated."); } catch { Alert.alert("Couldn’t save", "Please try again."); } finally { setBusy(false); } }
  async function exportData() { if (!guard() || !token || !user) return; setBusy(true); try { const data = await convex.query(api.customers.getDataExport, { token, customerId: user.customerId }); const file = new File(Paths.cache, `wearify-my-data-${new Date().toISOString().slice(0, 10)}.json`); file.create({ overwrite: true }); file.write(JSON.stringify(data, null, 2)); if (!(await Sharing.isAvailableAsync())) throw new Error("Sharing unavailable"); await Sharing.shareAsync(file.uri, { mimeType: "application/json", dialogTitle: "Save my Wearify data" }); } catch { Alert.alert("Couldn’t export data", "Please try again on this device."); } finally { setBusy(false); } }
  async function deleteData() { if (!guard() || !token || !user) return; setBusy(true); try { await remove({ token, customerId: user.customerId }); await auth.signOut(); } catch { Alert.alert("Couldn’t delete data", "Your account was not changed. Please try again."); } finally { setBusy(false); } }
  if (customer === undefined) return <><AppHeader back title="Privacy & data" /><Loading /></>;
  return <><AppHeader back title="Privacy & data" /><Screen><Title subtitle="Control how Wearify uses your information">Your Privacy</Title><View style={styles.card}><Consent label="Visit history" detail="Allow connected stores to view your visit and browsing history." value={history} set={setHistory} /><Consent label="WhatsApp messages" detail="Receive offers, reminders, and order updates." value={messages} set={setMessages} /><Consent label="Personalized styling" detail="Use your preferences to personalize recommendations." value={personal} set={setPersonal} /><Consent label="Photos" detail="Store your photos for virtual looks and wardrobe history." value={photos} set={setPhotos} /></View><PrimaryButton disabled={busy} onPress={() => void save()}>{busy ? "Please wait…" : "Save privacy choices"}</PrimaryButton><Title subtitle="A JSON copy containing your Wearify account information">Download my data</Title><SecondaryButton disabled={busy} onPress={() => Alert.alert("Download your data?", "The exported file may contain sensitive information. Store it securely.", [{ text: "Cancel", style: "cancel" }, { text: "Continue", onPress: () => void exportData() }])}>Prepare data export</SecondaryButton><View style={styles.danger}><Text style={styles.dangerTitle}>Delete my account and data</Text><Text style={styles.detail}>This permanently removes your Wearify customer data and cannot be undone.</Text><SecondaryButton disabled={busy} onPress={() => Alert.alert("Permanently delete your data?", "This cannot be undone.", [{ text: "Cancel", style: "cancel" }, { text: "Delete permanently", style: "destructive", onPress: () => void deleteData() }])}>Delete permanently</SecondaryButton></View></Screen></>;
}
function Consent({ label, detail, value, set }: { label: string; detail: string; value: boolean; set: (value: boolean) => void }) { return <View style={styles.row}><View style={{ flex: 1 }}><Text style={styles.label}>{label}</Text><Text style={styles.detail}>{detail}</Text></View><Switch accessibilityLabel={label} value={value} onValueChange={set} trackColor={{ false: colors.border, true: colors.brandSoft }} thumbColor={value ? colors.brand : colors.ghost} /></View>; }
const styles = StyleSheet.create({ card: { paddingHorizontal: 16, marginBottom: 18, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, row: { minHeight: 94, paddingVertical: 15, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, flexDirection: "row", alignItems: "center", gap: 14 }, label: { color: colors.ink, fontFamily: "Montserrat_600SemiBold", fontSize: 14 }, detail: { marginTop: 4, color: colors.muted, fontFamily: "DMSans_400Regular", fontSize: 12, lineHeight: 17 }, danger: { marginTop: 30, padding: 18, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.error, gap: 12 }, dangerTitle: { color: colors.error, fontFamily: "Montserrat_600SemiBold", fontSize: 15 } });
