import { Linking, Pressable, StyleSheet, Text, View } from "react-native";
import { useQuery } from "convex/react";
import { MapPin, MessageCircle, Navigation } from "lucide-react-native";
import { api } from "@/src/convex/api";
import { AppHeader, EmptyState, Loading, Screen, Title } from "@/src/components/ui";
import { useAuth } from "@/src/providers/auth";
import { colors, radius } from "@/src/theme/tokens";

export default function StoresScreen() {
  const { token, user } = useAuth(); const stores = useQuery(api.customers.listStoreLinksEnriched, token && user ? { token, customerId: user.customerId } : "skip");
  if (stores === undefined) return <><AppHeader back title="My stores" /><Loading /></>;
  return <><AppHeader back title="My stores" /><Screen><Title subtitle="Stores you’ve visited with Wearify">Connected Stores</Title>{stores.length === 0 ? <EmptyState title="No stores yet" detail="Your first in-store visit will appear here." /> : stores.map((store) => <View key={store._id} style={styles.card}><View style={styles.top}><View style={styles.pin}><MapPin color={colors.brand} size={21} /></View><View style={styles.copy}><Text style={styles.name}>{store.storeName ?? store.storeId}</Text><Text style={styles.meta}>{[store.storeCity, store.storeState].filter(Boolean).join(", ") || store.lastVisit || "Wearify partner"}</Text></View></View><Text style={styles.address}>{store.storeAddress ?? "Visit the store for details"}</Text><View style={styles.actions}>{store.phone ? <Action label="WhatsApp" icon={<MessageCircle color={colors.brand} size={17} />} onPress={() => void Linking.openURL(`https://wa.me/${store.phone?.replace(/\D/g, "")}`)} /> : null}<Action label="Directions" icon={<Navigation color={colors.brand} size={17} />} onPress={() => void Linking.openURL(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${store.storeName ?? store.storeId} ${store.storeCity ?? ""}`)}`)} /></View></View>)}</Screen></>;
}
function Action({ label, icon, onPress }: { label: string; icon: React.ReactNode; onPress: () => void }) { return <Pressable style={styles.action} onPress={onPress}>{icon}<Text style={styles.actionText}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ card: { marginBottom: 12, padding: 16, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, top: { flexDirection: "row", alignItems: "center", gap: 12 }, pin: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center", backgroundColor: colors.brandSoft }, copy: { flex: 1 }, name: { color: colors.ink, fontFamily: "Montserrat_600SemiBold", fontSize: 15 }, meta: { marginTop: 3, color: colors.muted, fontFamily: "DMSans_400Regular", fontSize: 12 }, address: { marginTop: 12, color: colors.muted, fontFamily: "DMSans_400Regular", fontSize: 13 }, actions: { marginTop: 14, flexDirection: "row", gap: 10 }, action: { flex: 1, minHeight: 44, borderRadius: radius.pill, borderWidth: 1, borderColor: colors.border, flexDirection: "row", gap: 7, alignItems: "center", justifyContent: "center" }, actionText: { color: colors.brand, fontFamily: "DMSans_600SemiBold", fontSize: 12 } });
