import { useState } from "react";
import { Alert, Linking, Pressable, StyleSheet, Text, View } from "react-native";
import { useMutation, useQuery } from "convex/react";
import { MessageCircle, Star } from "lucide-react-native";
import { api } from "@/src/convex/api";
import { AppHeader, EmptyState, Field, Loading, PrimaryButton, Screen, Title } from "@/src/components/ui";
import { useAuth } from "@/src/providers/auth";
import { useIsOnline } from "@/src/providers/connectivity";
import { colors, radius } from "@/src/theme/tokens";
import type { TailorOrder } from "@/src/types/domain";

const STEPS = ["confirmed", "measurements", "stitching", "ready", "delivered"];

export default function TailorOrdersScreen() {
  const { token, user } = useAuth(); const online = useIsOnline(); const orders = useQuery(api.tailorOps.listOrdersByCustomer, token && user ? { token, customerPhone: user.phone } : "skip"); const rate = useMutation(api.tailorOps.rateOrder);
  const [expanded, setExpanded] = useState<string>(); const [ratingOrder, setRatingOrder] = useState<TailorOrder["_id"]>(); const [rating, setRating] = useState(0); const [comment, setComment] = useState(""); const [busy, setBusy] = useState(false);
  if (orders === undefined) return <><AppHeader back title="My tailor orders" /><Loading /></>;
  async function submit() { if (!online) return Alert.alert("You’re offline", "Reconnect to submit a rating."); if (!ratingOrder || !token || rating === 0) return; setBusy(true); try { await rate({ token, id: ratingOrder, rating, ratingComment: comment.trim() || undefined }); setRatingOrder(undefined); setRating(0); setComment(""); } catch { Alert.alert("Couldn’t submit rating", "Please try again."); } finally { setBusy(false); } }
  return <><AppHeader back title="My tailor orders" /><Screen><Title subtitle={`${orders.filter((order) => order.status !== "delivered").length} active order(s)`}>Track your tailor journey</Title>{orders.length === 0 ? <EmptyState title="No tailor order yet" detail="Find a tailor through Wearify to get started." /> : orders.map((order) => { const open = expanded === order._id; const current = STEPS.indexOf(order.status ?? ""); return <View key={order._id} style={styles.card}><Pressable accessibilityRole="button" onPress={() => setExpanded(open ? undefined : order._id)}><View style={styles.top}><View style={{ flex: 1 }}><Text style={styles.name}>{order.tailorName ?? "Wearify tailor"}</Text><Text style={styles.meta}>{[order.service, order.saree].filter(Boolean).join(" · ")}</Text></View><Text style={styles.status}>{order.status ?? "confirmed"}</Text></View><View style={styles.progress}>{STEPS.map((step, index) => <View key={step} style={[styles.step, index <= current && styles.stepOn]} />)}</View><View style={styles.top}>{order.priceQuoted !== undefined ? <Text style={styles.price}>₹{order.priceQuoted.toLocaleString("en-IN")}</Text> : <View />}<Text style={styles.meta}>{order.dueDate ? `Due ${order.dueDate}` : order.orderDate}</Text></View></Pressable>{open ? <View style={styles.details}><Text style={styles.meta}>Order: {order.orderId ?? "—"}</Text>{order.fabric ? <Text style={styles.meta}>Fabric: {order.fabric}</Text> : null}{order.depositPaid !== undefined ? <Text style={styles.meta}>Deposit: ₹{order.depositPaid.toLocaleString("en-IN")}</Text> : null}{order.note ? <Text style={styles.note}>“{order.note}”</Text> : null}{order.tailorWhatsapp ? <Pressable style={styles.whatsapp} onPress={() => void Linking.openURL(`https://wa.me/${order.tailorWhatsapp?.replace(/\D/g, "")}`)}><MessageCircle color="#FFFFFF" size={17} /><Text style={styles.whatsappText}>Chat with tailor</Text></Pressable> : null}{order.status === "delivered" && !order.rating ? ratingOrder === order._id ? <View><Stars value={rating} set={setRating} /><Field label="Comment (optional)" value={comment} onChangeText={setComment} /><PrimaryButton disabled={busy || rating === 0} onPress={() => void submit()}>{busy ? "Submitting…" : "Submit rating"}</PrimaryButton></View> : <Pressable style={styles.rate} onPress={() => setRatingOrder(order._id)}><Text style={styles.rateText}>Rate tailor</Text></Pressable> : null}{order.rating ? <View><Stars value={order.rating} /><Text style={styles.note}>{order.ratingComment}</Text></View> : null}</View> : null}</View>; })}</Screen></>;
}
function Stars({ value, set }: { value: number; set?: (value: number) => void }) { return <View style={styles.stars}>{[1, 2, 3, 4, 5].map((star) => <Pressable key={star} disabled={!set} accessibilityRole={set ? "radio" : "image"} accessibilityLabel={`${value} out of 5 stars`} onPress={() => set?.(star)}><Star size={27} color="#B8860B" fill={star <= value ? "#B8860B" : "transparent"} /></Pressable>)}</View>; }
const styles = StyleSheet.create({ card: { marginBottom: 12, borderRadius: radius.lg, overflow: "hidden", borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, padding: 15 }, top: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 }, name: { color: colors.ink, fontFamily: "Montserrat_600SemiBold", fontSize: 14 }, meta: { marginTop: 3, color: colors.muted, fontFamily: "DMSans_400Regular", fontSize: 12 }, status: { color: colors.brand, fontFamily: "DMSans_600SemiBold", fontSize: 11, textTransform: "capitalize" }, progress: { marginVertical: 13, flexDirection: "row", gap: 3 }, step: { flex: 1, height: 4, borderRadius: 2, backgroundColor: colors.border }, stepOn: { backgroundColor: colors.brand }, price: { color: "#B8860B", fontFamily: "DMMono_500Medium", fontSize: 13 }, details: { marginTop: 14, paddingTop: 14, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border, gap: 8 }, note: { color: colors.muted, fontFamily: "DMSans_400Regular", fontSize: 12, fontStyle: "italic" }, whatsapp: { minHeight: 46, marginTop: 5, borderRadius: radius.pill, backgroundColor: "#25A95B", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, whatsappText: { color: "#FFFFFF", fontFamily: "DMSans_600SemiBold" }, rate: { minHeight: 46, borderRadius: radius.pill, borderWidth: 1, borderColor: colors.brand, alignItems: "center", justifyContent: "center" }, rateText: { color: colors.brand, fontFamily: "DMSans_600SemiBold" }, stars: { marginVertical: 10, flexDirection: "row", justifyContent: "center", gap: 7 } });
